// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/v1/chat_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import { file_google_api_resource } from "../../google/api/resource_pb";
import { file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/chat_service.proto.
 */
export const file_api_v1_chat_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvY2hhdF9zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEiHgoLQ2hhdFJlcXVlc3QSDwoHbWVzc2FnZRgBIAEoCSItCgxDaGF0UmVzcG9uc2USDwoHY29udGVudBgBIAEoCRIMCgR0eXBlGAIgASgJMnMKC0NoYXRTZXJ2aWNlEmQKBENoYXQSGS5tZW1vcy5hcGkudjEuQ2hhdFJlcXVlc3QaGi5tZW1vcy5hcGkudjEuQ2hhdFJlc3BvbnNlIiOC0+STAh06ASoiGC9hcGkvdjEvY2hhdC9jb21wbGV0aW9uczABQqgBChBjb20ubWVtb3MuYXBpLnYxQhBDaGF0U2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vdXNlbWVtb3MvbWVtb3MvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_api_resource, file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * @generated from message memos.api.v1.ChatRequest
 */
export type ChatRequest = Message<"memos.api.v1.ChatRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message memos.api.v1.ChatRequest.
 * Use `create(ChatRequestSchema)` to create a new message.
 */
export const ChatRequestSchema: GenMessage<ChatRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_service, 0);

/**
 * @generated from message memos.api.v1.ChatResponse
 */
export type ChatResponse = Message<"memos.api.v1.ChatResponse"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;

  /**
   * 思考内容 正式文本内容 搜索内容等等
   *
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message memos.api.v1.ChatResponse.
 * Use `create(ChatResponseSchema)` to create a new message.
 */
export const ChatResponseSchema: GenMessage<ChatResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_service, 1);

/**
 * @generated from service memos.api.v1.ChatService
 */
export const ChatService: GenService<{
  /**
   * 关键点：returns (stream ChatResponse)
   *
   * @generated from rpc memos.api.v1.ChatService.Chat
   */
  chat: {
    methodKind: "server_streaming";
    input: typeof ChatRequestSchema;
    output: typeof ChatResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_chat_service, 0);

